[package]
name = "circom-proof-schema"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"
authors = ["TACEO GmbH <hello@taceo.io>"]
homepage = "https://www.taceo.io"
repository = "https://github.com/TaceoLabs/circom_proof_schema"
license = "MIT OR Apache-2.0"
publish = false
readme = "./README.md"

[dependencies]
ark-ec = "^0.6.0"
ark-ff = "^0.6.0"
ark-groth16 = "^0.6.0"
ark-poly = "^0.6.0"
ark-relations = "^0.6.0"
co-circom = { git = "https://github.com/TaceoLabs/co-snarks", rev = "0252321cde491082854ef976fc45264d5a7eadab", version = "0.10.0" }
eyre = "0.6.12"
rand = "0.8.5"
rayon = "1.9.0"
